Convert API response JSON to Python dict
ProdPerfect/monday pull request #26
Opened 2021-05-18 20:11 UTC by lucioseki

Some methods in this library are returning the API response JSON
string without converting it to a Python dict.
This is forcing the caller to selectively call `json.loads`
depending on the retrieved resource (e.g. `users` resource requires
`json.loads`, but `items` doesn't).

This patch makes all the API responses to be converted to a Python
dict, so the caller can consistently use the return value as a dict
regardless the requested resource.

2021-05-18 20:12 UTC, lucioseki commented
This PR addresses the issue #25

2021-05-19 16:24 UTC, chdastolfo approved these changes
👍

2021-05-19 17:33 UTC, rhymiz requested changes
@lucioseki my proposal here is to change `response.text` to `response.json()` in the graphql client. That's the source of the issue.

Note: `requests` will raise an exception if you call `.json` on a response object that does not contain a 2xx or 4xx status code, that can either be handle explicitly by you, or you can call `response.raise_for_status()` before moving on to calling `response.json`.

2021-05-19 21:46 UTC, rhymiz commented on monday/resources/base.py
> +from monday.exceptions import MondayError
did you mean to import these?

2021-05-19 21:48 UTC, lucioseki commented on monday/resources/base.py
> +from monday.exceptions import MondayError
oops, I didn't

2021-05-19 23:08 UTC, rhymiz approved these changes
This looks good! Thanks for addressing all the comments!

2021-05-20 01:13 UTC, merged